version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  build:
    docker: 
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    environment:
      SLACK_WEBHOOK: https://hooks.slack.com/services/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
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - slack/status:
          include_project_field: true


          